import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Outfit } from "next/font/google";
import Provider from "./provider";
import { Toaster } from "@/components/ui/sonner";
import { UserDetailProvider } from "./_context/UserDetailContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      appearance={{ baseTheme: outfit.className }}
      dynamic={true}
    >
      <UserDetailProvider>
        <html lang="en">
          <body className={outfit.className}>
            <Provider>{children}</Provider>
            <Toaster />
          </body>
        </html>
      </UserDetailProvider>
    </ClerkProvider>
  );
}
